[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'


remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${VULTISIG_INFURA_KEY}"